"use client";
import { useState } from "react";
import Link from "next/link";
import { Header, Footer, CALENDLY } from "./site-shell";
const solutions=[{n:"01",title:"Inquiry Capture",copy:"Bring phone, web, and social inquiries into one organized intake flow—day or night.",meta:"Voice · Web · SMS"},{n:"02",title:"Intelligent Follow-Up",copy:"Keep families informed with timely messages, reminders, and clear human handoffs.",meta:"SMS · Email · Tasks"},{n:"03",title:"Staffing Readiness",copy:"Compare new-client needs with caregiver availability before promising a start date.",meta:"Capacity · Matching · Handoff"}];
export default function Home(){
 const [inquiries,setInquiries]=useState(40),[missed,setMissed]=useState(30),[closeRate,setCloseRate]=useState(25),[value,setValue]=useState(4500),[priority,setPriority]=useState("intake");
 const leakage=Math.round(inquiries*(missed/100)*(closeRate/100)*value);
 const recommendations:Record<string,[string,string]>={intake:["24/7 Intake Capture","Create a reliable first response across calls, forms, and messages."],followup:["Follow-Up Engine","Give every qualified inquiry a clear next step until they book or decline."],staffing:["Staffing Readiness","Check service needs against caregiver capacity before the handoff."],visibility:["Owner Visibility","See sources, response times, statuses, and bottlenecks in one place."]};
 return <main id="top"><Header/>
 <section className="hero"><div className="hero-copy"><p className="eyebrow"><span/> Built for senior-care operators</p><h1>Turn every inquiry into a <em>clear path to care.</em></h1><p className="lede">CAREINTAKEAI designs connected growth and operations systems for private-pay home care, memory care, residential care, group homes, and adult day programs—without adding more administrative chaos.</p><div className="actions"><Link className="button primary" href="/book">Book Your System Audit <b>↗</b></Link><Link className="button ghost" href="/audit">Find My Best Starting System</Link></div><div className="trust"><span>Human handoff built in</span><span>Nonclinical workflows</span><span>Built around your care model</span></div></div>
 <div className="flow-visual" aria-label="Interactive intake workflow"><div className="flow-top"><span>LIVE INTAKE FLOW</span><i>● System ready</i></div><div className="family-card"><small>NEW FAMILY INQUIRY</small><strong>“We need care for Mom this week.”</strong><span>Call received · 7:42 PM</span></div><div className="flow-line"><i/><i/><i/></div><div className="flow-grid"><article><b>01</b><strong>Captured</strong><span>Need and location recorded</span></article><article><b>02</b><strong>Qualified</strong><span>Coordinator receives context</span></article><article><b>03</b><strong>Booked</strong><span>Consultation confirmed</span></article></div><div className="flow-result"><span>✓</span><div><small>NEXT ACTION</small><strong>Care coordinator follow-up</strong></div><b>9:00 AM</b></div></div></section>
 <section className="signal-strip"><span>Capture every inquiry</span><i/><span>Respond with context</span><i/><span>Protect human judgment</span><i/><span>See what happens next</span></section>
 <section className="experience-band"><div><p className="kicker">START WITH YOUR REALITY</p><h2>A different care model needs a different starting point.</h2><p>Choose the fastest path for you: get a tailored system recommendation, explore services by care setting, or book a focused audit.</p></div><div className="experience-actions"><Link className="button primary" href="/audit">Find My System <b>→</b></Link><Link className="button ghost" href="/services">Explore by Care Setting</Link><Link className="text-link" href="/book">Book an Audit <b>↗</b></Link></div></section>
 <section className="section light" id="systems"><div className="section-head"><div><p className="kicker">01 / THE OPERATING GAP</p><h2>More leads will not fix a <em>broken handoff.</em></h2></div><p>Families decide quickly. Your team is already busy. We connect the moments between first contact, follow-up, consultation, and staffing—without pretending automation should replace care.</p></div><div className="solution-grid">{solutions.map(s=><article key={s.n}><span>{s.n}</span><div className="solution-icon">{s.n==="01"?"☎":s.n==="02"?"↗":"◇"}</div><h3>{s.title}</h3><p>{s.copy}</p><small>{s.meta}</small></article>)}</div><a className="text-link" href="/services">Explore all CAREINTAKEAI systems <b>↗</b></a></section>
 <section className="section dark diagnostic" id="diagnostic"><div className="diagnostic-copy"><p className="kicker">02 / START WITH THE BOTTLENECK</p><h2>What is creating the most friction today?</h2><p>Choose one. We’ll show you the most practical place to start—not the largest possible project.</p><div className="choices">{[["intake","Calls or inquiries go unanswered"],["followup","Leads disappear after first contact"],["staffing","New cases are difficult to staff"],["visibility","I cannot see what is working"]].map(([id,label])=><button className={priority===id?"active":""} onClick={()=>setPriority(id)} key={id}><i/>{label}<b>→</b></button>)}</div></div><div className="recommendation"><small>YOUR RECOMMENDED START</small><div className="pulse-icon">✦</div><h3>{recommendations[priority][0]}</h3><p>{recommendations[priority][1]}</p><a className="button primary" href={CALENDLY} target="_blank" rel="noreferrer">Discuss this starting point <b>↗</b></a></div></section>
 <section className="section light calculator" id="calculator"><div><p className="kicker">03 / OPPORTUNITY ESTIMATOR</p><h2>Estimate the cost of slow or missed follow-up.</h2><p>This planning tool is directional—not a revenue promise. Results depend on lead quality, service capacity, pricing, and actual conversion.</p><div className="formula">INQUIRIES × MISSED % × CLOSE RATE × CLIENT VALUE</div></div><div className="calc-card">
 <label><span>Monthly inquiries <b>{inquiries}</b></span><input aria-label="Monthly inquiries" type="range" min="5" max="150" value={inquiries} onChange={e=>setInquiries(Number(e.target.value))}/></label>
 <label><span>Missed or delayed <b>{missed}%</b></span><input aria-label="Missed or delayed" type="range" min="5" max="70" value={missed} onChange={e=>setMissed(Number(e.target.value))}/></label>
 <label><span>Consult-to-client rate <b>{closeRate}%</b></span><input aria-label="Consult-to-client rate" type="range" min="5" max="70" value={closeRate} onChange={e=>setCloseRate(Number(e.target.value))}/></label>
 <label><span>Estimated first-month value <b>${value.toLocaleString()}</b></span><input aria-label="Estimated first-month value" type="range" min="1000" max="15000" step="500" value={value} onChange={e=>setValue(Number(e.target.value))}/></label>
 <div className="result"><small>Potential monthly opportunity leakage</small><strong>${leakage.toLocaleString()}</strong><span>Planning estimate—not guaranteed revenue.</span></div><a className="button primary full" href={CALENDLY} target="_blank" rel="noreferrer">Find the Leak in Your Workflow <b>↗</b></a></div></section>
 <section className="section process"><p className="kicker">04 / A CONTROLLED IMPLEMENTATION</p><h2>Designed around your team.<br/><em>Measured in your workflow.</em></h2><div className="process-grid">{[["01","Audit","Map the real inquiry, referral, follow-up, and staffing journey."],["02","Design","Choose the smallest connected system that solves the highest-value bottleneck."],["03","Build + Test","Configure safeguards, human handoffs, and reporting before launch."],["04","Improve","Train the team, review the data, and refine what is not working."]].map(([n,t,c])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></section>
 <section className="cta"><p className="kicker">THE NEXT BEST STEP</p><h2>Find the operational leak<br/>before buying more software.</h2><p>Book a focused audit. We’ll map the bottleneck, decide whether automation is appropriate, and identify the clearest starting point.</p><div className="actions center"><a className="button primary" href={CALENDLY} target="_blank" rel="noreferrer">Book Your CAREINTAKEAI Audit <b>↗</b></a><a className="button ghost" href="tel:+16785610670">Call 678-561-0670</a></div></section><Footer/></main>}
